### ISSUE TITLE
please rename file1 variable

### ISSUE THREAD

**Issue by jasonwalsh** [smulhall1337/misc#1]
https://github.com/smulhall1337/misc/blob/ab7eb9b088b73c5b4b4a0da0e42bd3f14896adbb/file-diff.py#L5

i really don' lt like the name

**Comment by smulhall1337** [comment]
Please open a pull rerquest with the name you lkike

**Comment by smulhall1337** [comment]
https://github.com/smulhall1337/Warehouse-Inventory-Scanner/pull/2
